/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.rosewooddev.io/repository/public/")
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.+")
    compileOnly("dev.rosewood:rosestacker:1.5.39")
    compileOnly("com.github.hyperdefined:hyperlib:1.0.14:all")
}

group = "lol.hyper"
version = "2.0.4"
description = "ToolStats"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

val pluginVersion = version.toString()

tasks.processResources {
    filteringCharset = "UTF-8"

    val props = mapOf("version" to pluginVersion)
    inputs.properties(props)

    filesMatching("paper-plugin.yml") {
        expand(props)
    }
}