name: ToolStats
version: ${version}
main: lol.hyper.toolstats.ToolStats
api-version: '26.1.1'
folia-supported: true
author: hyperdefined
description: Track various tool stats!
website: https://github.com/hyperdefined/ToolStats

loader: lol.hyper.toolstats.ToolStatsLoader

permissions:
  toolstats.command:
    description: Allows the usage of /toolstats.
    default: true
    children:
      toolstats.reset: true
      toolstats.reset.confirm: true
      toolstats.purge: true
      toolstats.purge.confirm: true
  toolstats.reload:
    description: Allows the usage of /toolstats reload.
    default: op
  toolstats.givetokens:
    description: Allows the usage of /toolstats givetoken.
    default: op
  toolstats.edit:
    description: Allows the usage of /toolstats edit.
    default: op
  toolstats.remove:
    description: Allows the usage of /toolstats remove.
    default: op

dependencies:
  server:
    RoseStacker:
      load: BEFORE
      required: false