name: ToolStats
version: '${project.version}'
main: lol.hyper.toolstats.ToolStats
api-version: 1.21
author: hyperdefined
description: Track various tool stats!
website: https://github.com/hyperdefined/ToolStats
folia-supported: true
commands:
  toolstats:
    usage: /toolstats
    permission: toolstats.command
permissions:
  toolstats.command:
    description: Allows the usage of /toolstats.
    default: true
  toolstats.reload:
    description: Allows the usage of /toolstats reload.
    default: op
  toolstats.reset:
    description: Allows the usage of /toolstats reset.
    default: true
  toolstats.reset.confirm:
    description: Allows the usage of /toolstats reset confirm.
    default: true
  toolstats.givetokens:
    description: Allows the usage of /toolstats givetoken.
    default: op
  toolstats.edit:
    description: Allows the usage of /toolstats edit.
    default: op
  toolstats.remove:
    description: Allows the usage of /toolstats remove.
    default: op